name: Docker Build
on:
  push:
    tags:
      - 'alpine-*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set env
        run: echo "ALPINE_VERSION=${GITHUB_REF#*-}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/kvaps/alpine-socat:${{ env.ALPINE_VERSION }}
          build-args: |
            ALPINE_IMAGE=alpine:${{ env.ALPINE_VERSION }}
